name: api_handling
description: "Learning Api with Bloc and dio"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  bloc: ^8.1.4
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.5
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  flutter_hooks: ^0.20.5
  rxdart: ^0.28.0
  animated_splash_screen: ^1.3.0
  email_validator: ^3.0.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  flutter_slidable: ^3.1.2
  connectivity_plus: ^6.1.2
  get: ^4.6.6
  provider: ^6.1.2
  flutter_localization: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
